dist: xenial # required for Python >= 3.7
language: python
python:
  - "3.7"

services:
  - postgresql

env:
  - SECRET_KEY='coolsecretinformation'

install:
  - pip install -r requirements.txt

script:
  - coverage run --source='allauthdjango/apps' manage.py test && coverage report

after_success:
  - coveralls
