# Generated by Django 2.2.1 on 2019-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(default='linkedin', max_length=25),
            preserve_default=False,
        ),
    ]
